### ISSUE TITLE
Don't use ng- prefix

### ISSUE THREAD

**Issue by lukasolson** [jeffling/ng-tether#4]
Looks like an awesome library. I'm a little hesitant to use it because it uses the ng- prefix. Can we just take out this prefix or choose a different prefix? Using the ng- prefix gives the impression that this directive is built and supported by the Angular team, which I assume is not the case.

**Comment by bubbleheadinc** [comment]
+1

**Comment by jeffling** [comment]
name is now 

1) more awkward
2) more correct 

:)

**Comment by lukasolson** [comment]
:+1: Thanks!
